massalabs/massa-sc-toolkit

- README.md
- package-lock.json
- package.json
- packages/sc-project-initializer/commands/init/package-lock.json
Upgrade package to fit with as types
> Update Package to fit with as-types

- .github/workflows/node.js.yml
- .github/workflows/npm-publish-dev.yml
- .github/workflows/npm-publish.yml
- README.md
- package-lock.json
- package.json
- packages/sc-compiler/package.json
- packages/sc-compiler/src/compiler.ts
- packages/sc-deployer/package.json
- packages/sc-project-initializer/commands/init/assembly/contracts/main.ts
- packages/sc-project-initializer/commands/init/package-lock.json
- packages/sc-project-initializer/commands/init/package.json
- packages/sc-project-initializer/commands/init/src/deploy.ts
- scripts/publish-dev.sh
This PR has no associated issue. 
This PR will fix the build steps and the CD, as well as this issue: https://github.com/massalabs/massa-sc-toolkit/issues/77
> :construction_worker: refactor build, fix CD

- packages/sc-deployer/README.md
- packages/sc-deployer/src/index.ts
- packages/sc-project-initializer/commands/init/src/deploy.ts
We will need to do a new release of deployer and project-initializer
> [feat] add max_coins field

- packages/sc-project-initializer/commands/init/.github/workflows/ci-tests.yml
> update node-version from 16 to 18

- packages/sc-deployer/README.md
- packages/sc-project-initializer/commands/init/.env.example
- packages/sc-project-initializer/commands/init/README.md
- packages/sc-project-initializer/commands/init/src/deploy.ts
> Consistent names secret key instead of private key

- .github/LICENSE
> add License to root

- packages/sc-project-initializer/CONTRIBUTING.md
> adding Contributing.md to initializer

- .github/workflows/powered-by.yml
- generate_powered-by.sh
- packages/sc-deployer/powered-by.md
- packages/sc-project-initializer/powered-by.md
> 170 add powered by to sc-deployer & sc-project-initializer

- packages/sc-project-initializer/LICENSE
> add License to initializer

- packages/sc-deployer/CONTRIBUTING.md
> sc-deployer add contributing

- packages/sc-project-initializer/src/initialize.js
> update initialize.ts doc

- packages/sc-project-initializer/src/cli.js
> add documentation to src/cli.js

- packages/sc-project-initializer/commands/init/.github/workflows/ci-tests.yml
> ci instead of install for run command

- packages/sc-deployer/src/index.ts
> fix toMAS conversion

- packages/sc-deployer/src/index.ts
> Update index.ts doc

- packages/sc-deployer/src/index.ts
- packages/sc-deployer/src/interfaces.ts
- packages/sc-deployer/src/utils/index.ts
- packages/sc-deployer/src/utils/maxCoins.ts
> add maxCoins estimation

- packages/sc-deployer/README.md
> update sc-deployer README

- CONTRIBUTING.md
> Contributing.md at root dir

- packages/sc-deployer/README.md
> added details about max_coins

- packages/sc-project-initializer/commands/init/README.md
> update readme of init

- .github/workflows/node.js.yml
- jest.config.ts
- package-lock.json
- package.json
- packages/sc-deployer/asconfig.json
- test/test.spec.ts
> setup jest

- packages/sc-deployer/asconfig.json
- packages/sc-project-initializer/commands/init/asconfig.json
- packages/sc-project-initializer/commands/init/package.json
> 209 allow compiler to use protobuf transformer

- packages/massa-proto-cli/src/as-gen.ts
- packages/massa-proto-cli/src/index.ts
- packages/massa-proto-cli/src/ts-gen.ts
> Extend the cli of Massa-Proto-Cli to use ts-gen

- packages/massa-proto-cli/LICENSE.md
> add LICENSE.md (MIT)

- .github/workflows/powered-by.yml
- packages/massa-proto-cli/powered-by.md
> Update powered-by.yml to genererate powered-by.md for massa-proto-cli

- packages/massa-proto-cli/src/index.ts
it only gets protofiles.  Callers are not generated
closes #347
> add protofile retrieving without generting callers

- package.json
- packages/massa-proto-cli/src/index.ts
- packages/sc-project-initializer/commands/init/package.json
> Install automatically the necessary dependencies 
